#!/usr/bin/env python3

import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from runtest import cli, run
from runtest_config import configure

options = cli()
ierr = run(options,
           configure,
           input_files=['field_from_density.inp'],
           output_files=[
               (
                   'FQSolver_results/field_from_density_fld.txt',
                   'reference/FQSolver_results/field_from_density_fld.txt',
               )
           ])

sys.exit(ierr)
