#!/usr/bin/env python3

import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from runtest import get_filter, cli, run
from runtest_config import configure

f = [
    get_filter(from_string='Associated molecular coordinates',
               to_string='We should',
               rel_tolerance=1.0e-15)
]

options = cli()
ierr = run(options,
           configure,
           input_files=['potential_from_density.inp'],
           filters={'log': f})

sys.exit(ierr)
